###

GET http://localhost:3333/media

###

POST http://localhost:3333/media HTTP/1.1
Content-Type: application/json

{    
    "title": "This should be a unique title",
    "url": "http://google.com",
    "author": "Tom Sawyer",    
    "description": "This is a comment",
    "mediaType": "video",
    "dateSubmitted": "04/05/2020"
}